#Calculating area of a rectangle using a float.....
#With L representing Length and W representing width we are using a float allowing for decimal measurements...
L = float(input("Length of Rectangle: "))
W = float(input("Width of Rectangle: "))
#Below area is the equivalent of L * W......
area = (L * W)
#Print statement below gives us the area L * W.....
print("The area of the Rectangle is: " , (area))